name: Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: compile wasm
        working-directory: ./src/wasm
        run: wasm-pack build
      - name: build
        run: |
          npm ci
          npm run build
          mv dist/index.html dist/404.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist